services:
  postgres:
    restart: unless-stopped
    ports: !reset []

  geoserver:
    restart: unless-stopped
    ports: !reset []

  backend:
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120
    ports: !reset []
    volumes: !override
      - ./data:/app/data
      - ./geoserver:/geoserver
      - ./scripts:/app/scripts
      - backend_media:/app/media

  frontend:
    restart: unless-stopped
    command: npm run start
    ports: !reset []
    volumes: !reset []

  nginx:
    restart: unless-stopped
    ports:
      - "8890:80"
      # - "443:443"
