# Generated by Django 4.2.30 on 2026-07-09 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatasWilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=255, verbose_name='Nama Wilayah')),
                ('jenis', models.CharField(choices=[('desa', 'Desa'), ('dusun', 'Dusun')], max_length=50, verbose_name='Jenis Wilayah')),
                ('luas_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Luas (Ha)')),
                ('kode_wilayah', models.CharField(blank=True, max_length=100, verbose_name='Kode Wilayah')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Batas Geometri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Batas Wilayah',
                'verbose_name_plural': 'Batas Wilayah',
                'db_table': 'batas_wilayah',
            },
        ),
        migrations.CreateModel(
            name='PotensiInfrastruktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Fasilitas')),
                ('jenis_fasilitas', models.CharField(max_length=255, verbose_name='Jenis Fasilitas')),
                ('kondisi', models.CharField(blank=True, max_length=255, verbose_name='Kondisi')),
                ('kapasitas', models.CharField(blank=True, max_length=255, verbose_name='Kapasitas')),
                ('pengelola', models.CharField(blank=True, max_length=255, verbose_name='Pengelola')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Titik Lokasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Potensi Infrastruktur',
                'verbose_name_plural': 'Potensi Infrastruktur',
                'db_table': 'potensi_infrastruktur',
            },
        ),
        migrations.CreateModel(
            name='PotensiPertanian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Potensi')),
                ('komoditas', models.CharField(max_length=255, verbose_name='Komoditas')),
                ('luas_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Luas (Ha)')),
                ('nama_pemilik', models.CharField(blank=True, max_length=255, verbose_name='Nama Pemilik')),
                ('kontak', models.CharField(blank=True, max_length=100, verbose_name='Kontak')),
                ('hasil_panen', models.CharField(blank=True, max_length=255, verbose_name='Hasil Panen')),
                ('musim_tanam', models.CharField(blank=True, max_length=255, verbose_name='Musim Tanam')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='Foto')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Potensi Pertanian',
                'verbose_name_plural': 'Potensi Pertanian',
                'db_table': 'potensi_pertanian',
            },
        ),
        migrations.CreateModel(
            name='PotensiUMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_usaha', models.CharField(max_length=255, verbose_name='Nama Usaha')),
                ('jenis_produk', models.CharField(max_length=255, verbose_name='Jenis Produk')),
                ('nama_pemilik', models.CharField(max_length=255, verbose_name='Nama Pemilik')),
                ('kontak', models.CharField(blank=True, max_length=100, verbose_name='Kontak')),
                ('jam_operasional', models.CharField(blank=True, max_length=255, verbose_name='Jam Operasional')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='Foto')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Titik Lokasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Potensi UMKM',
                'verbose_name_plural': 'Potensi UMKM',
                'db_table': 'potensi_umkm',
            },
        ),
        migrations.CreateModel(
            name='PotensiWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Wisata/Budaya')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('jam_kunjungan', models.CharField(blank=True, max_length=255, verbose_name='Jam Kunjungan')),
                ('harga_tiket', models.CharField(blank=True, max_length=100, verbose_name='Harga Tiket')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='Foto')),
                ('kontak', models.CharField(blank=True, max_length=100, verbose_name='Kontak')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Potensi Wisata & Budaya',
                'verbose_name_plural': 'Potensi Wisata & Budaya',
                'db_table': 'potensi_wisata',
            },
        ),
    ]
