# Generated by Django 4.2.30 on 2026-09-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensipertanian',
            name='foto_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Daftar Foto'),
        ),
        migrations.AddField(
            model_name='potensiumkm',
            name='foto_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Daftar Foto'),
        ),
        migrations.AddField(
            model_name='potensiwisata',
            name='foto_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Daftar Foto'),
        ),
    ]
