# Generated by Django 4.2.30 on 2026-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi', '0002_potensipertanian_foto_list_potensiumkm_foto_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potensiinfrastruktur',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='potensiinfrastruktur',
            name='foto_list',
            field=models.JSONField(blank=True, default=list, verbose_name='Daftar Foto'),
        ),
        migrations.AddField(
            model_name='potensiinfrastruktur',
            name='kontak',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kontak'),
        ),
    ]
