# Generated by Django 4.2.30 on 2026-09-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potensi', '0003_potensiinfrastruktur_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=255, verbose_name='Nama Desa')),
                ('kecamatan', models.CharField(max_length=255, verbose_name='Kecamatan')),
                ('kabupaten', models.CharField(max_length=255, verbose_name='Kabupaten')),
                ('provinsi', models.CharField(max_length=255, verbose_name='Provinsi')),
                ('kode_pos', models.CharField(blank=True, default='', max_length=10, verbose_name='Kode Pos')),
                ('jumlah_penduduk', models.PositiveIntegerField(default=0, verbose_name='Jumlah Penduduk')),
                ('jumlah_penduduk_laki', models.PositiveIntegerField(default=0, verbose_name='Penduduk Laki-laki')),
                ('jumlah_penduduk_perempuan', models.PositiveIntegerField(default=0, verbose_name='Penduduk Perempuan')),
                ('jumlah_kk', models.PositiveIntegerField(default=0, verbose_name='Jumlah KK')),
                ('luas_wilayah_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Luas Wilayah (Ha)')),
                ('jumlah_dusun', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah Dusun')),
                ('jumlah_rw', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah RW')),
                ('jumlah_rt', models.PositiveSmallIntegerField(default=0, verbose_name='Jumlah RT')),
                ('visi', models.TextField(blank=True, default='', verbose_name='Visi')),
                ('misi', models.JSONField(blank=True, default=list, verbose_name='Misi')),
                ('sejarah', models.TextField(blank=True, default='', verbose_name='Sejarah Desa')),
                ('deskripsi', models.TextField(blank=True, default='', verbose_name='Deskripsi Singkat')),
                ('alamat_kantor', models.TextField(blank=True, default='', verbose_name='Alamat Kantor')),
                ('telepon', models.CharField(blank=True, default='', max_length=50, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('jam_pelayanan', models.CharField(blank=True, default='', max_length=255, verbose_name='Jam Pelayanan')),
                ('foto_hero', models.ImageField(blank=True, null=True, upload_to='desa/', verbose_name='Foto Hero')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Profil Desa',
                'verbose_name_plural': 'Profil Desa',
                'db_table': 'desa_profile',
            },
        ),
    ]
